[Plt-6621] tests for Accordion component
riipen/ui pull request #146
Opened 2021-02-10 21:06 UTC by licarm

## Description

- tests for the Accordion component
- focus, blur, focusVisible removed from AccordionSummary

2021-02-10 21:59 UTC, imogenem requested changes
Just small changes, looks great

2021-02-10 21:59 UTC, imogenem commented on packages/riipen-ui/src/components/Accordion.test.jsx
> +    it("applies disabled class when true", () => {
Just to make the test name really clear, should this be "applies disabled class name when disabled is true"

2021-02-10 21:59 UTC, imogenem commented on packages/riipen-ui/src/components/Accordion.test.jsx
> +    it("does not apply disabled class when false", () => {
Same change needed to test name

2021-02-10 21:59 UTC, imogenem commented on packages/riipen-ui/src/components/Accordion.test.jsx
> +
I was able to test the default classes value for Button, does this work for you?

```
 expect(wrapper.find("Accordion").props().classes).toEqual([]);
```

2021-02-11 01:53 UTC, jordanell requested changes

2021-02-11 01:53 UTC, jordanell commented on packages/riipen-ui/src/components/Accordion.test.jsx
> +    const child = <AccordionDetails />;
I don't think these need to be variables. I would just render them inline on lines 29-30.

2021-02-11 01:53 UTC, jordanell commented on packages/riipen-ui/src/components/Accordion.test.jsx
> +  });
I don't think this test is right. We aren't testing something is being rendered. We are essentially doing:

1. Give AccordionDetails a child
2. Test did we give according details a child

I think a better test could be "does wrapped contain the child node".

2021-02-11 01:53 UTC, jordanell commented on packages/riipen-ui/src/components/Accordion.test.jsx
> +      ).toEqual(true);
This might be a good candidate for 2 separate tests. Thoughts?

2021-02-11 01:53 UTC, jordanell commented on packages/riipen-ui/src/components/Accordion.test.jsx
> +      ).toEqual(false);
Maybe two separate tests again?

2021-02-11 01:53 UTC, jordanell commented on packages/riipen-ui/src/components/Accordion.test.jsx
> +      const child = <AccordionDetails>hello</AccordionDetails>;
Not sure these need to be in variables. Could just in-line them.

2021-02-11 01:53 UTC, jordanell commented on packages/riipen-ui/src/components/Accordion.test.jsx
> +      const child = <AccordionDetails>hello</AccordionDetails>;
This doesn't really need to be in a variable.

2021-02-11 01:53 UTC, jordanell commented on packages/riipen-ui/src/components/Accordion.test.jsx
> +      const child = <AccordionDetails>hello</AccordionDetails>;
Again, probably doesn't need to be a variable.

2021-02-11 01:53 UTC, jordanell commented on packages/riipen-ui/src/components/Accordion.test.jsx
> +      const child = <AccordionDetails>hello</AccordionDetails>;
Same here with variable.

2021-02-11 20:52 UTC, jordanell approved these changes

2021-02-11 21:53 UTC, imogenem approved these changes

2021-02-11 23:18 UTC, merged