[PLT-6623] Tests for AccordionSummary
riipen/ui pull request #148
Opened 2021-02-11 20:20 UTC by imogenem

## Description
Tests for AccordionSummary

## Notes
Warning for onFocusVisible appears but all tests pass. Once Accordion is merged with master, should be able to run without the warning.

## Where to Start
AccordionSummary.test.jsx

2021-02-12 17:48 UTC, licarm requested changes
Nice!! Just one thing.

2021-02-12 17:48 UTC, licarm commented on packages/riipen-ui/src/components/AccordionSummary.test.jsx
> +  });
You can assert that the provided icon is being rendered using the assertion .containsMatchingElement() or .contains().

2021-02-13 18:02 UTC, jordanell requested changes
Nice job!

2021-02-13 18:02 UTC, jordanell commented on packages/riipen-ui/src/components/AccordionSummary.test.jsx
> +  describe("iconProps prop", () => {
I think we should add another test here. The `iconProps` prop also looks like it passes `iconProps.classes` to the icon `classes` here https://github.com/riipen/ui/blob/eed21d980e392b67816338eb5cfc816c5e877746/packages/riipen-ui/src/components/AccordionSummary.jsx#L94. 

So let's add a test to make sure that happens.

2021-02-16 18:14 UTC, jordanell approved these changes

2021-02-16 18:20 UTC, licarm approved these changes

2021-02-16 18:20 UTC, licarm commented on packages/riipen-ui/src/components/AccordionSummary.test.jsx
> +      );
Look great!

2021-02-16 18:21 UTC, merged