[PLT-6620] Add Riipen UI to CodeClimate
riipen/ui pull request #156
Opened 2021-02-22 22:37 UTC by licarm

## Where to Start
./.circleci/config.yml

2021-02-22 23:48 UTC, imogenem approved these changes

2021-02-23 00:06 UTC, imogenem approved these changes

2021-02-23 00:15 UTC, jordanell requested changes
CircleCI stuff looks good. We should remove the `tmp/` files though. Let's first remove them from the repo then make sure `tmp/` is in the git ignore.

2021-02-23 22:40 UTC, jordanell approved these changes
Sweeeeeet

2021-02-23 23:00 UTC, imogenem approved these changes

2021-02-23 23:15 UTC, merged