Allow buttons to take icons and components that render icons
riipen/ui pull request #172
Opened 2021-03-23 23:31 UTC by stredger

## Description

Allow the button to render icons directly instead of having to pass a component in

## Notes

## Screenshots

## Where to Start

2021-03-23 23:32 UTC, stredger commented on packages/riipen-ui-docs/src/pages/components/button/Icons.jsx
> -
allows us to get rid of this on web

2021-03-23 23:32 UTC, stredger commented on packages/riipen-ui-docs/src/pages/components/button/Icons.jsx
> +      >
and just use like this

2021-03-23 23:34 UTC, jordanell requested changes

2021-03-23 23:34 UTC, jordanell commented on packages/riipen-ui/src/components/Button.jsx
> +  iconStart: PropTypes.oneOfType([PropTypes.elementType, PropTypes.node]),
Nice! We should add tests to encompass this new functionality.

2021-03-23 23:41 UTC, daelynj commented on packages/riipen-ui/src/components/Button.jsx
> +              {typeof IconStart === "function" ? <IconStart /> : IconStart}
Yeah definitely add tests for the cases when `IconStart` and End are functions and when they're not.

2021-03-24 00:12 UTC, daelynj approved these changes
Nice work!!

2021-03-24 03:11 UTC, jordanell approved these changes

2021-03-24 17:41 UTC, merged