Add end prop to Input component, rename icon to start
riipen/ui pull request #190
Opened 2021-04-07 21:51 UTC by ksmort

## Description
Update `icon` prop to be `start`.  Add `end` prop, which displays content on the right side of the input, similar to the `start` prop.  Remove default icon colour, reorganize css.
Update docs and tests.

## Screenshots
![Screenshot_2021-04-07 Input Riipen UI(5)](https://user-images.githubusercontent.com/10818279/113939281-a6002e00-97b0-11eb-8798-8becd32d2b60.png)

## Where to Start
packages/riipen-ui/src/components/Input.jsx

2021-04-07 21:55 UTC, ksmort commented on packages/riipen-ui-docs/src/pages/components/input/input.md
> +## Start and End
Not sure if I should call this "Controls"?

2021-04-07 21:55 UTC, ksmort commented on packages/riipen-ui/src/components/Input.jsx
> +          position: relative;
Add position relative so that the start/end position absolute is relative to the wrapper.

2021-04-07 23:38 UTC, jordanell requested changes
Looks good. Just a suggestion around naming.

2021-04-07 23:38 UTC, jordanell commented on packages/riipen-ui/src/components/Input.jsx
> +  end,
I wonder if we can be slightly more descriptive with these? Maybe just straight copy material-ui with endAdornment and startAdornment?

2021-04-08 02:37 UTC, jordanell approved these changes

2021-04-08 16:45 UTC, merged