[PLT-7424] Add color prop to Avatar
riipen/ui pull request #214
Opened 2021-06-01 19:48 UTC by ericauv

## Description
* Add a `color` prop to `<Avatar>`, defaults to "grey" and can be one of "grey" or "white"
## Notes

## Screenshots
Avatar with background white, others with default grey background
![Screen Shot 2021-06-01 at 3 08 07 PM](https://user-images.githubusercontent.com/36321777/120381660-bb955e00-c2f0-11eb-8fc3-c31a920cea89.png)

## Where to Start

2021-06-01 20:23 UTC, jordanell reviewed
@ericauv I'm not entirely convinced this is the way to go. We already have `classes` which can be set to something with a specific background color. Just curious why we want to make it an explicit prop with this PR.

2021-06-01 20:30 UTC, ericauv commented
> @ericauv I'm not entirely convinced this is the way to go. We already have `classes` which can be set to something with a specific background color. Just curious why we want to make it an explicit prop with this PR.

Most of our other `ui` components have a color prop, I think this change makes sense because it makes the use of our ui components more consistent.
I think we should either always use the color prop to set background-color of our ui components, or always use classes --> I think using the color prop is an easier/cleaner dev experience

2021-06-02 15:49 UTC, jordanell commented
@ericauv that's fair. I think we should call this one `backgroundColor` though to distinguish it from other foreground color props.

2021-06-03 15:29 UTC, jordanell requested changes

2021-06-03 15:29 UTC, jordanell commented on packages/riipen-ui/src/components/Avatar.jsx
> +    backgroundColor: PropTypes.oneOf(["grey", "white"]),
Sorry I should have caught this earlier. When we use greys in our props, we have the standard of using the fully qualified grey like "grey200", "grey600", or "greyA400", so I think in this case, we should probably use `grey200`.

2021-06-03 15:39 UTC, jordanell approved these changes

2021-06-03 15:43 UTC, merged